[theme]
primaryColor = "#9db2a3"  # Muted sage green
backgroundColor = "#f4f4f4"  # Light background for better contrast
secondaryBackgroundColor = "#e0e6de"  # Slightly darker sage for secondary elements
textColor = "#333333"  # Dark text for readability
